source: "Miscellaneous"
recipes:

#
- name: Chas
  author: Murray Stenson
  url: https://cocktailpartyapp.com/drinks/chas/
  notes: |+2
      "One of the regulars at the Zig Zag Cafe loved his bourbon cocktails, to the point of never having anything else. There are, of course, only so many bourbon cocktail recipes out there, so one time he asked Murray to come up with something different, and this was the result. The customers name was Charles, or 'Chaz' to his friends."
  glassware: coupe
  ingredients:
  - 2½ ounces Bourbon
  - ¼ ounce Amaretto or Crème de noyaux
  - ¼ ounce Bénédictine
  - ¼ ounce Cointreau
  - ¼ ounce Grand Marnier
  steps:
  - Combine all ingredients with ice in a mixing glass and stir.
  - Strain into a coupe glass.
  - No garnish.
  tags:
  - stirred
  - zig zag zig
- name: The Weeper's Joy
  author: 
  url: https://cocktailvirgin.blogspot.com/2019/02/the-weepers-joy.html
  notes: |+2
      
  glassware: nick & nora
  ingredients:
  - 1/4 ounce simple syrup
  - 3/4 ounce Kübler Absinthe
  - 3/4 ounce Cocchi Storico Vermouth di Torino
  - 3/4 ounce Kümmel
  - 1/4 ounce Pierre Ferrand Dry Curacao
  steps:
  - Combine all ingredients with ice in a mixing glass and stir.
  - Strain into a coupe glass.
  - No garnish.
  tags:
  - stirred
- name: Fino Noir
  author: Yanni Kehagiaras
  url: https://www.drinkmagazine.asia/2018/02/15/fino-noir-yanni-kehagiaras/
  notes: |+2
      
  glassware: nick & nora
  ingredients:
  - 60ml Manzanilla sherry
  - 20ml Averna
  - "Garnish: orange twist"
  steps:
  - Stir the ingredients over ice, strain into a cocktail glass or copita and garnish with an orange twist.
  tags:
  - stirred
  - stoa
- name: Promises, Promises
  author: Nick Jarrett
  url: https://www.instagram.com/fredericyarm/p/C6VYP9UuD9W/
  notes: |+2
      
  glassware: rocks
  ingredients:
  - 1 1/2 oz Plymouth gin
  - 3/4 oz Cocchi Americano
  - 1/4 oz Giffard Pamplemousse
  - 7 drops Bittermens Grapefruit Bitters
  - "Garnish: orange twist"
  steps:
  - Stir with ice, strain into a double old fashioned glass with ice, and garnish with an orange twist.
  tags:
  - stirred
  - cure
  - martini
  - freezer bar
- name: Roku Koori Negroni
  author: 
  url: https://www.theeducatedbarfly.com/roku-koori-negroni/
  notes: |+2
      
  glassware: rocks
  ingredients:
  - 3/4 oz ice wine
  - 1/4 oz red wine vinegar
  - 1/2 oz bitter bianco
  - 1 1/2 oz Roku gin
  - "Garnish: grapefruit twist"
  steps:
  - Stir with ice, strain into a double old fashioned glass with ice, and garnish with a grapefruit twist.
  tags:
  - stirred
  - negroni