source: "Substack"
recipes:

#
  - name: Cherry Lady
    author: Jackson Mercier
    year: 2023
    glassware: coupe
    ingredients:
    - 3/4 ounce apple brandy
    - 3/4 ounce gin
    - 1/2 ounce lemon juice
    - 1/2 ounce simple syrup
    - 1/2 ounce tart cherry juice
    steps:
    - Combine the ingredients in a cocktail shaker half filled with ice. 
    - Shake until chilled, about 15 seconds. 
    - Strain into a chilled coupe.
    tags:
    - shaken
    - citrus
  - name: Her Name Is Rio
    author: Abigail Gullo
    year: 2021
    glassware: nick & nora
    ingredients:
    - 2 ounces cachaça
    - 3/4 ounce sweet tea syrup (either commercial brand or simple syrup made with brewed tea instead of water)
    - Juice of 1 lime
    - 1 egg white
    - 2 to 3 fresh pitted cherries
    steps:
    - Muddle the cherries in a cocktail shaker with the sweet tea syrup. 
    - Add the lime juice, egg white and cachaça. 
    - Dry shake without ice. 
    - Add ice and shake until chilled, about 15 seconds. 
    - Double strain into chilled cocktail glass.
    tags:
    - shaken
    - citrus
  - name: Smoky, Artsy, Autumnal Sour
    year: 2023
    glassware: rocks
    ingredients:
    - ⅜ ounce 3:1 honey syrup
    - ⅜ ounce ginger syrup
    - ¾ ounce fresh lemon juice
    - ¼ ounce smoky Scotch, preferably Laphroaig 10
    - 1¾ ounce apple brandy, preferably Laird's Straight Bottled-in-Bond
    - Mist of Angostura bitters from a spray bottle
    steps:
    - Combine all ingredients except Angostura bitters in a cocktail shaker.
    - Add ice, then shake until chilled, about 10-12 seconds. 
    - Strain into a rocks glass over a single large piece of ice. 
    - Using a small spray bottle, spray a mist layer of Angostura onto the top of the drink. (If you don't have a mist bottle, simply take a scant barspoon of Angostura bitters and very gently pour it over the top of the drink. You're trying to float a very, very fine layer of bitters at the top of the mix.)
    tags:
    - autumn
    - peaty
    - shaken
    - citrus
  - name: The Riddler #1
    year: 2023
    author: Phil Ward
    glassware: nick & nora
    ingredients:
    - 2 ounces Hayman’s London Dry Gin
    - 2 ounces Cocchi Americano
    - 5 dashes of Peychaud's Bitters
    - "Garnish: grapefruit twist"
    steps:
    - Combine ingredients in a mixing glass half-filled with ice. 
    - Stir until chilled, about 15 seconds. 
    - Express a grapefruit twist over the surface of the drink and discard.
    tags:
    - martini
    - stirred
    - freezer bar
  - name: The Riddler #2
    year: 2023
    author: Phil Ward
    glassware: nick & nora
    ingredients:
    - 2 ounces Hayman’s London Dry Gin
    - 2 ounces Cocchi Americano
    - 5 dashes of Angostura Bitters
    - "Garnish: grapefruit twist"
    steps:
    - Combine ingredients in a mixing glass half-filled with ice. 
    - Stir until chilled, about 15 seconds. 
    - Express a grapefruit twist over the surface of the drink and discard.
    tags:
    - martini
    - stirred
    - freezer bar
  - name: Jack Rose
    year: 2024
    url: https://archive.is/TKkCm#selection-2785.0-2792.0
    author: Brian Miller
    glassware: nick & nora
    ingredients:
    - 2 ounces Laird’s Bonded Apple Brandy
    - ½ ounce fresh lemon juice
    - ½ ounce fresh lime juice
    - ½ ounce grenadine (1½ cups POM Wonderful pomegranate juice & 1 cup turbinado sugar, combined over low heat and stirred until sugar has dissolved)
    - ¼ ounce simple syrup
    - ¼ ounce Crème de Framboise
    steps:
    - In a shaker half-filled with ice, combine ingredients. 
    - Shake until chilled, about 15 seconds. 
    - Strain into a chilled coupe.
    tags:
    - shaken
    - citrus